name: Recreate Stage Branch on PR Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  recreate-stage-branch:
    if: >
      github.event.pull_request.merged == true &&
      contains(join(github.event.pull_request.labels.*.name, ' '), 'recreate-stage') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Recreate stage branch from main
        run: |
          git fetch origin
          # Delete remote stage branch
          git push origin --delete stage || echo "stage branch does not exist"
          # Recreate stage branch from main
          git checkout main
          git pull origin main
          git checkout -b stage
          git push origin stage --force
