name: Update Test Failure Analysis JSON file

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize   # runs on new commits pushed to PR
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  update-json:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'change-report-database') }}
    steps:
      - name: Check Java version and install Java 21 if not present
        id: setup_java
        run: |
          JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d. -f1)
          if [ "$JAVA_VERSION" != "21" ]; then
            echo "Java 21 not found. Installing Java 21..."
            sudo apt-get update
            sudo apt-get install -y openjdk-21-jdk
            echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" >> $GITHUB_ENV
            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
          else
            echo "Java 21 is already installed."
          fi
        shell: bash

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Check changed files
        id: files
        run: |
          git fetch origin main
          git diff --name-only origin/main > changed_files.txt
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          cat changed_files.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run condition check
        id: check_change
        run: |
          changed_files="${{ steps.files.outputs.changed_files }}"
          echo "Files changed since main:"
          echo "$changed_files"
          update_needed="false"
          if echo "$changed_files" | grep -q "src/main/java/factory/SoftAssertionMessages.java"; then
            if ! echo "$changed_files" | grep -q "src/main/java/reportingHelper/dataset/testFailureAnalysis.json"; then
              update_needed="true"
            fi
          fi
          echo "update_needed=$update_needed" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run update if needed
        if: steps.check_change.outputs.update_needed == 'true'
        run: |
          echo "Running maven command to update JSON"
          mvn compile exec:java -Dexec.mainClass="reportingHelper.AddNewDataToJson"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/main/java/reportingHelper/dataset/testFailureAnalysis.json
          git commit -m "chore: update testFailureAnalysis.json from SoftAssertionMessages.java changes" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}

      - name: Notify no update needed
        if: steps.check_change.outputs.update_needed == 'false'
        run: echo "No update to testFailureAnalysis.json needed."

